feat: add ability to attach access tags to resources
terraform-ibm-modules/terraform-ibm-icd-postgresql pull request #166
Opened 2023-04-25 17:21 UTC by MatthewLemmond

### Description
Add access tags to the postgresql resource created by the module and update tests

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [x] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content
Add ability to attach access tags to resources created by the module, consumers who want to use the access tags will need additional permissions for Tagging service at the Administrator level

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-05-09 17:24 UTC, SirSpidey requested changes
I think I caught all the user content about tags.

2023-05-09 17:24 UTC, SirSpidey commented on README.md
> +        - `Administrator` platform access
```suggestion
To attach access management tags to resources in this module, you need the following permissions.

- IAM Services
    - **Tagging** service
        - `Administrator` platform access
```

If it's optional, you don't "need" it.

2023-05-09 17:24 UTC, SirSpidey commented on examples/complete/variables.tf
> +  description = "Optional list of access management tags to be added to created resources"
```suggestion
  description = "Optional list of access management tags to add to resources that are created"
```

2023-05-09 17:24 UTC, SirSpidey commented on examples/default/variables.tf
> +  description = "Optional list of access management tags to be added to created resources"
```suggestion
  description = "Optional list of access management tags to add to resources that are created"
```

2023-05-09 17:24 UTC, SirSpidey commented on examples/fscloud/variables.tf
> +  description = "Optional list of access management tags to be added to created resources"
```suggestion
  description = "Optional list of access management tags to add to resources that are created"
```

2023-05-09 17:24 UTC, SirSpidey commented on examples/pitr/variables.tf
> +  description = "Optional list of access management tags to be added to created resources"
```suggestion
  description = "Optional list of access management tags to add to resources that are created"
```

2023-05-09 17:24 UTC, SirSpidey commented on examples/replica/variables.tf
> +  description = "Optional list of access management tags to be added to created resources"
```suggestion
  description = "Optional list of access management tags to add to resources that are created"
```

2023-05-09 17:24 UTC, SirSpidey commented on module-metadata.json
> +      "description": "A list of access tags to apply to the resources created by the module, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial for more details",
```suggestion
      "description": "A list of access tags to apply to the resources created by the module. For more information, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial.",
```

2023-05-09 17:24 UTC, SirSpidey commented on profiles/fscloud/variables.tf
> +  description = "Optional list of access management tags to be added to created resources"
```suggestion
  description = "Optional list of access management tags to add to resources that are created"
```

2023-05-09 17:24 UTC, SirSpidey commented on variables.tf
> +  description = "A list of access tags to apply to the resources created by the module, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial for more details"
```suggestion
  description = "A list of access tags to apply to the resources created by the module. For more information, see https://cloud.ibm.com/docs/account?topic=account-access-tags-tutorial."
```

2023-05-18 22:38 UTC, MatthewLemmond commented
The PR test is failing with:
```Error updating database cpu auto_scaling group: Request failed with status code: 422, ServerErrorResponse: {"errors":{"cpu.rate.limit_count_per_member":["cannot autoscale higher than regular scaling limit"]}}```

From what I can see none of the scaling variables were affected by my PR (diffs only show addition of access tag variables), is there a change that was recently merged that I need to account for/add a variable for in order to pass the test?

2023-05-19 17:52 UTC, MatthewLemmond commented
Looks like that resolved the issue, thanks @ocofaigh @shemau!

2023-05-22 08:16 UTC, ocofaigh requested changes
Can you update all the variable description. Access tags only get applied to the postgres instance as far as I can see, so perhaps update:

`to apply to the resources created by the module` -> `to apply to the PostgreSQL instance created by the module`

2023-05-22 18:04 UTC, SirSpidey submitted a review, later dismissed
Content updates look good. Thanks.

2023-05-22 18:10 UTC, ocofaigh commented on profiles/fscloud/variables.tf
> +  description = "Optional list of access management tags to add to resources that are created"
Should match the variable description in the root level variables.tf

2023-05-23 10:07 UTC, ocofaigh approved these changes

2023-05-23 10:08 UTC, merged