feat: add description value in ibm_iam_authorization_policy block
terraform-ibm-modules/terraform-ibm-icd-postgresql pull request #269
Opened 2023-08-29 12:17 UTC by Khuzaima05

### Description

Pass description value to ibm_iam_authorization_policy block.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-08-29 12:17 UTC, Khuzaima05 commented
/run pipeline

2023-09-04 12:32 UTC, Khuzaima05 commented
@ocofaigh Can I skip the upgrade test here, Pipeline is failing due to this.

2023-09-04 16:10 UTC, ocofaigh commented
@Khuzaima05 yes I think this is fine. As per the log, its going to simply update the description of the existing auth policy, so no impact to consumers..

```
Messages:   	Resource(s) identified to be updated Name: kms_policy Address: module.postgresql_db.ibm_iam_authorization_policy.kms_policy[0] Actions: [update]
        	            	DIFF:
        	            	Before: {"description":null}
        	            	After: {"description":"Allow all ICD Postgres instances in the resource group ee8675e51c5d4ef5aec89b49c5a1b7b5 to read from the kms instance GUID 3082d097-48e5-4adb-b613-77e348d40c89"}
```

2023-09-04 16:39 UTC, Khuzaima05 commented
/run pipeline

2023-09-04 19:21 UTC, ocofaigh commented on main.tf
> +  description                 = "Allow all ICD Postgres instances in the resource group ${var.resource_group_id}  to read from the ${local.kms_service} instance GUID ${var.existing_kms_instance_guid}
remove the double space after `${var.resource_group_id}`

2023-09-04 19:22 UTC, ocofaigh requested changes
one minor comment

2023-09-05 06:22 UTC, Khuzaima05 commented
/run pipeline

2023-09-05 08:45 UTC, ocofaigh approved these changes

2023-09-05 08:46 UTC, merged

2023-09-05 08:48 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.5.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/releases/tag/v3.5.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: