fix: introduce new input variable use_default_backup_encryption_key
terraform-ibm-modules/terraform-ibm-icd-postgresql pull request #294
Opened 2023-10-05 13:44 UTC by akocbek

### Description

Add a new boolean variable called use_default_backup_encryption_key (defaulting to false) which allows consumers to opt in to use the the default ICD key in order to allow them to provision to regions that do not support BYOK backup encryption.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-10-05 13:44 UTC, akocbek commented
/run pipeline

2023-10-05 14:00 UTC, ocofaigh requested changes
The `backup_encryption_key_crn` variable descrption now needs to be updated. Update this sentence:

`If no value is passed here, the value passed for the 'kms_key_crn' variable is used.` -> `If no value is passed here, the value passed for the 'kms_key_crn' variable is used, unless 'use_default_backup_encryption_key' is set to 'true'.`

Also we now need to add validation to ensure that a value cannot be passed for `backup_encryption_key_crn` if `use_default_backup_encryption_key` is set to `true`. This should work (not tested):

```
validate_backup_key = var.backup_encryption_key_crn != null && var.use_default_backup_encryption_key == true ? tobool("When passing a value for 'backup_encryption_key_crn' you cannot set 'use_default_backup_encryption_key' to 'true'") : true
```

2023-10-05 14:00 UTC, ocofaigh commented on variables.tf
> +  description = "Set to true to use the default ICD key."
Set to true to use default ICD randomly generated keys

2023-10-05 14:27 UTC, akocbek commented
/run pipeline

2023-10-05 14:37 UTC, akocbek commented
@ocofaigh thank you for review.

2023-10-06 10:33 UTC, akocbek commented
/run pipeline

2023-10-06 11:50 UTC, ocofaigh approved these changes

2023-10-06 11:53 UTC, merged

2023-10-06 11:54 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.7.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/releases/tag/v3.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: