docs: improve consumability and accuracy of fscloud doc
terraform-ibm-modules/terraform-ibm-icd-postgresql pull request #47
Opened 2023-03-01 12:42 UTC by vburckhardt

### Description

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.

### Types of changes in this PR

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] The PR references a GitHub issue.
- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

2023-03-01 15:04 UTC, SirSpidey requested changes
@vburckhardt A bunch of style suggestions. Let me know if it's too hard to commit these suggestions and I can make a PR to this PR instead.

2023-03-01 15:04 UTC, SirSpidey commented on profiles/fscloud/README.md
> +:exclamation: The financial services framework mandates the application of an inbound network-based allow-list in front of the ICD PostGresql instance. This can be achieved in multiple ways:
```suggestion
:exclamation: **Important:** The Financial Services framework mandates the application of an inbound network-based allowlist in front of the ICD PostgreSQL instance. You can comply in multiple ways:
```

2023-03-02 08:42 UTC, maheshwarishikha commented on examples/fscloud/main.tf
> +# Postgres Instance (FsCloud Profile)
It should be FSCloud.

2023-03-08 21:23 UTC, SirSpidey commented
@vburckhardt wanted to make sure you saw my comments on this PR. It has been open for a week.

2023-04-24 18:28 UTC, SirSpidey commented
@vburckhardt checking in again on this open PR. I see that you made some updates. What is left (besides addressing conflicts)?

2023-05-10 19:42 UTC, SirSpidey commented
@vburckhardt Does the `/profiles/fscloud/readme.md` content in #185 cover this PR?

2023-05-11 17:41 UTC, ocofaigh commented
Updates included in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/186

2023-05-11 17:41 UTC, closed without merging